# -*- coding: utf-8 -*-
"""streamlit_app_bryan_ly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fMGZUIotI5OgIQOLah_r-5ZPdVMH4WEO

## Streamlit Integration
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Page title and layout
st.set_page_config(
    page_title="CPS Weekly Earnings Explorer",
    layout="wide"
)

st.title("CPS Weekly Earnings Explorer")

st.write(
    "This app allows users to explore weekly earnings by education level, "
    "sex, and survey year using Current Population Survey data."
)


# Load and clean the data
@st.cache_data
def load_data():
    data = pd.read_csv("cps_project_data (1).csv")

    data["UHRSWORKT"] = data["UHRSWORKT"].replace([997, 999], np.nan)

    data["SEX_LABEL"] = data["SEX"].map({
        1: "Male",
        2: "Female"
    })

    def get_education_group(code):
        if 2 <= code <= 71:
            return "Less than High School"
        elif code == 73:
            return "High School Diploma"
        elif code == 81:
            return "Some College"
        elif code == 91 or code == 92:
            return "Associate Degree"
        elif code == 111:
            return "Bachelor's Degree"
        elif 123 <= code <= 125:
            return "Graduate Degree"
        else:
            return np.nan

    data["EDUC_GROUP"] = data["EDUC"].apply(get_education_group)

    return data


df = load_data()

# Education options
education_order = [
    "Less than High School",
    "High School Diploma",
    "Some College",
    "Associate Degree",
    "Bachelor's Degree",
    "Graduate Degree"
]


# Sidebar filters
st.sidebar.header("Filters")

selected_education = st.sidebar.multiselect(
    "Select education level:",
    education_order,
    default=education_order
)

minimum_year = int(df["YEAR"].min())
maximum_year = int(df["YEAR"].max())

selected_years = st.sidebar.slider(
    "Select year range:",
    minimum_year,
    maximum_year,
    (minimum_year, maximum_year)
)

selected_sex = st.sidebar.radio(
    "Select sex:",
    ["All", "Male", "Female"]
)


# Filter data
filtered_df = df[
    df["EDUC_GROUP"].isin(selected_education)
]

filtered_df = filtered_df[
    filtered_df["YEAR"].between(
        selected_years[0],
        selected_years[1]
    )
]

if selected_sex != "All":
    filtered_df = filtered_df[
        filtered_df["SEX_LABEL"] == selected_sex
    ]


# Stop if no data matches
if filtered_df.empty:
    st.warning(
        "No records match the selected filters. "
        "Please change your selections."
    )
    st.stop()


# Summary values
worker_count = len(filtered_df)
mean_earnings = filtered_df["EARNWEEK2"].mean()
median_earnings = filtered_df["EARNWEEK2"].median()


# Display summary values
column1, column2, column3 = st.columns(3)

column1.metric(
    "Number of Workers",
    f"{worker_count:,}"
)

column2.metric(
    "Mean Weekly Earnings",
    f"${mean_earnings:,.2f}"
)

column3.metric(
    "Median Weekly Earnings",
    f"${median_earnings:,.2f}"
)


# Summary statistics table
st.subheader("Summary Statistics by Education Level")

summary_table = filtered_df.groupby(
    "EDUC_GROUP"
)["EARNWEEK2"].agg(
    ["count", "mean", "median", "std"]
)

summary_table = summary_table.round(2)

summary_table.columns = [
    "Worker Count",
    "Mean Earnings",
    "Median Earnings",
    "Standard Deviation"
]

st.dataframe(summary_table)


# Bar chart
st.subheader("Average Weekly Earnings by Education Level")

chart_data = filtered_df.groupby(
    "EDUC_GROUP"
)["EARNWEEK2"].mean()

chart_data = chart_data.reindex(
    education_order
).dropna()

fig, ax = plt.subplots(figsize=(10, 5))

ax.bar(
    chart_data.index,
    chart_data.values
)

ax.set_title(
    "Average Weekly Earnings by Education Level"
)

ax.set_xlabel("Education Level")
ax.set_ylabel("Average Weekly Earnings ($)")

plt.xticks(
    rotation=30,
    ha="right"
)

plt.tight_layout()

st.pyplot(fig)


# Optional raw data preview
st.subheader("Filtered Data Preview")

st.dataframe(
    filtered_df[
        [
            "YEAR",
            "AGE",
            "SEX_LABEL",
            "EDUC_GROUP",
            "UHRSWORKT",
            "EARNWEEK2"
        ]
    ].head(100)
)